name: Run Unit Tests

on:
  pull_request:
    branches:
      - main

jobs:
   install-deps:
    uses: ./.github/workflows/install-dependencies.yml
    with:
      fallback-node-version: '18'

   test:
    needs: install-deps
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code # Clone repository's code into the workflow's virtual machine
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Run unit tests
        run: npm test -- --watchAll=false
