name: Run Unit Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code # Clone repository's code into the workflow's virtual machine
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION || '18' }} # A fallback to node v.18 if fails to get the node version from .nvmrc file

      - name: Cache node modules
        uses: actions/cache@v3
        id: npm-cache
        with:
          path: |
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci # Get dependencies from cached instead of installing it everytime to save time

      - name: Run unit tests
        run: npm test -- --watchAll=false # If we stop here the worklow will fail if any test fail and PR couldn't be merged, but we want to give just a warning and allow PR merge, so we add the following lines
      #   continue-on-error: true

      # - name: Check if tests failed and warn
      #   if: failure()
      #   run: echo "::warning::Some unit tests failed. Please review the logs above."

      # - name: Comment on PR if tests fail # Add comment on PR if test fails
      #   if: steps.run-tests.outcome != 'success'
      #   uses: actions/github-script@v7
      #   with:
      #     script: |
      #       github.rest.issues.createComment({
      #         issue_number: context.issue.number,
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         body: '⚠️ Warning: Unit tests failed. Please review the test results in the Actions logs.'
      #       });
